apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
  creationTimestamp: null
  name: bmcs.infra.io.odimra
spec:
  group: infra.io.odimra
  names:
    kind: Bmc
    listKind: BmcList
    plural: bmcs
    singular: bmc
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.bmcSystemId
      name: SystemID
      type: string
    - jsonPath: .status.serialNumber
      name: SerialNumber
      type: string
    - jsonPath: .status.vendorName
      name: Vendor
      type: string
    - jsonPath: .status.modelID
      name: ModelID
      type: string
    - jsonPath: .status.firmwareVersion
      name: FirmwareVersion
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: Bmc is the Schema for the bmcs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: BmcSpec defines the desired state of Bmc
            properties:
              bmc:
                properties:
                  address:
                    type: string
                  connectionMethodVariant:
                    type: string
                  powerState:
                    type: string
                  resetType:
                    type: string
                required:
                - address
                - connectionMethodVariant
                - powerState
                - resetType
                type: object
              credentials:
                properties:
                  password:
                    type: string
                  username:
                    type: string
                required:
                - password
                - username
                type: object
            required:
            - bmc
            type: object
          status:
            description: BmcStatus defines the observed state of Bmc
            properties:
              biosAttributeRegistry:
                type: string
              biosVersion:
                type: string
              bmcAddStatus:
                type: string
              bmcSystemId:
                type: string
              eventsMessageRegistry:
                type: string
              firmwareVersion:
                type: string
              modelID:
                type: string
              powerState:
                type: string
              serialNumber:
                type: string
              storageControllers:
                additionalProperties:
                  description: ArrayControllers defines the storage controllers for BMC
                  properties:
                    drives:
                      additionalProperties:
                        description: DriveDetails defines the drive details for specific Array Controller
                        properties:
                          capacityBytes:
                            type: string
                          usedInVolumes:
                            items:
                              type: integer
                            type: array
                        required:
                        - capacityBytes
                        - usedInVolumes
                        type: object
                      type: object
                    supportedRAIDLevel:
                      items:
                        type: string
                      type: array
                  required:
                  - drives
                  - supportedRAIDLevel
                  type: object
                type: object
              systemReset:
                type: string
              vendorName:
                type: string
            required:
            - biosAttributeRegistry
            - biosVersion
            - bmcAddStatus
            - bmcSystemId
            - firmwareVersion
            - modelID
            - powerState
            - serialNumber
            - systemReset
            - vendorName
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}