apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
  creationTimestamp: null
  name: firmwares.infra.io.odimra
spec:
  group: infra.io.odimra
  names:
    kind: Firmware
    listKind: FirmwareList
    plural: firmwares
    singular: firmware
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Firmware is the Schema for the firmwares API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Bmcs should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Bmcs may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: FirmwareSpec defines the desired state of Firmware
            properties:
              image:
                properties:
                  auth:
                    properties:
                      password:
                        type: string
                      username:
                        type: string
                    type: object
                  imageLocation:
                    type: string
                required:
                - imageLocation
                type: object
              transferProtocol:
                type: string
            required:
            - image
            type: object
          status:
            description: FirmwareStatus defines the observed state of Firmware
            properties:
              firmwareVersion:
                type: string
              imagePath:
                type: string
              status:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}